name: FloatingTips
author: lorenzo.stanco
category: Interface
tags: [tip, tooltip, balloon, tips]
demo: http://jsfiddle.net/SLvUz/483/
docs: http://wiki.github.com/lorenzos/FloatingTips/docs
current: 2.9
sources:
  - "Source/FloatingTips.js"
  - "Source/FloatingTips.Dialog.js"
